name = "matematik-egitsel-materyaller"
compatibility_date = "2024-10-23"

# Cloudflare Pages configuration
pages_build_output_dir = "."

[env.production]
name = "matematik-egitsel-materyaller"

[env.preview]
name = "matematik-egitsel-materyaller-preview"
